# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b4d0acc597ab8759f3b0f2465acb93888ab656691f3720d7859de4418395cb8ba57ebfc8bc8cff7b7cdfc0e66a682a313eaf001242aa4806c62b6fc243b93055

test:
  secret_key_base: bbf70cbe6093d5890fff453af2eee8bdc58ab84eb6a9b4844a20c20a57ce1e55b852c0e143b5f8504dd800e5a142861d5231b8ff930012973fa36cf50be83cb9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
